version: "3"

services:
  srv-app-sessions:
    build: ./srv-app-sessions
    command: ["node", "--watch-path=./src", "src/index"]
    restart: always
    environment:
      - SERVICE_NAME=srv-app-sessions
    volumes:
      - ./srv-app-sessions/src:/app/src
    container_name: srv-app-sessions
    env_file:
      - ./.env

  auth-simple:
    build:
      context: ./auth-simple
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev", "--", "--host"]
    container_name: auth-simple
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=auth-simple
      - OTP_ENABLED=false
      - OTP_APP_NAME=NELREINATECH
      - OTP_SESSION_EXPIRED=3600
      - TRANSLATION_ENABLED=false
      - ALLOWED_ROLES=ADMIN
    volumes:
      - ./auth-simple/src:/appsrc/src
      - ./auth-simple/static:/appsrc/static
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth-simple.rule=Host("skp.auth-simple.localhost")
    env_file:
      - ./.env

  testapp:
    build:
      context: ./testapp
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev", "--", "--host"]
    container_name: testapp
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=testapp
      - OTP_ENABLED=false
      - OTP_APP_NAME=NELREINATECH
      - OTP_SESSION_EXPIRED=3600
    volumes:
      - ./testapp/src:/appsrc/src
      - ./testapp/static:/appsrc/static
    labels:
      - traefik.enable=true
      - traefik.http.routers.testapp.rule=Host("app.testapp.localhost")
      - traefik.frontend.passHostHeader='true'
    env_file:
      - ./.env

  global-state:
    build:
      context: ./global-state
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev", "--", "--host"]
    container_name: global-state
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=global-state
      - OTP_ENABLED=false
      - OTP_APP_NAME=NELREINATECH
      - OTP_SESSION_EXPIRED=3600
    volumes:
      - ./global-state/src:/appsrc/src
      - ./global-state/static:/appsrc/static
    labels:
      - traefik.enable=true
      - traefik.http.routers.global-state.rule=Host("app.global-state.localhost")
    env_file:
      - ./.env

networks:
  default:
    name: traefik
    external: true
